// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/transport/grpc/detector/proto/detector.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	mi := &file_internal_transport_grpc_detector_proto_detector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_detector_proto_detector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_detector_proto_detector_proto_rawDescGZIP(), []int{0}
}

func (x *DetectRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *DetectRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_internal_transport_grpc_detector_proto_detector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_detector_proto_detector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_detector_proto_detector_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Contour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*Point               `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contour) Reset() {
	*x = Contour{}
	mi := &file_internal_transport_grpc_detector_proto_detector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contour) ProtoMessage() {}

func (x *Contour) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_detector_proto_detector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contour.ProtoReflect.Descriptor instead.
func (*Contour) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_detector_proto_detector_proto_rawDescGZIP(), []int{2}
}

func (x *Contour) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type DetectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contours      []*Contour             `protobuf:"bytes,1,rep,name=contours,proto3" json:"contours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	mi := &file_internal_transport_grpc_detector_proto_detector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_detector_proto_detector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_detector_proto_detector_proto_rawDescGZIP(), []int{3}
}

func (x *DetectResponse) GetContours() []*Contour {
	if x != nil {
		return x.Contours
	}
	return nil
}

var File_internal_transport_grpc_detector_proto_detector_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_detector_proto_detector_proto_rawDesc = "" +
	"\n" +
	"5internal/transport/grpc/detector/proto/detector.proto\x12\bdetector\"I\n" +
	"\rDetectRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"2\n" +
	"\aContour\x12'\n" +
	"\x06points\x18\x01 \x03(\v2\x0f.detector.PointR\x06points\"?\n" +
	"\x0eDetectResponse\x12-\n" +
	"\bcontours\x18\x01 \x03(\v2\x11.detector.ContourR\bcontours2M\n" +
	"\x0eObjectDetector\x12;\n" +
	"\x06Detect\x12\x17.detector.DetectRequest\x1a\x18.detector.DetectResponseB1Z/thesis_back/internal/transport/grpc/proto;protob\x06proto3"

var (
	file_internal_transport_grpc_detector_proto_detector_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_detector_proto_detector_proto_rawDescData []byte
)

func file_internal_transport_grpc_detector_proto_detector_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_detector_proto_detector_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_detector_proto_detector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_detector_proto_detector_proto_rawDesc), len(file_internal_transport_grpc_detector_proto_detector_proto_rawDesc)))
	})
	return file_internal_transport_grpc_detector_proto_detector_proto_rawDescData
}

var file_internal_transport_grpc_detector_proto_detector_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_transport_grpc_detector_proto_detector_proto_goTypes = []any{
	(*DetectRequest)(nil),  // 0: detector.DetectRequest
	(*Point)(nil),          // 1: detector.Point
	(*Contour)(nil),        // 2: detector.Contour
	(*DetectResponse)(nil), // 3: detector.DetectResponse
}
var file_internal_transport_grpc_detector_proto_detector_proto_depIdxs = []int32{
	1, // 0: detector.Contour.points:type_name -> detector.Point
	2, // 1: detector.DetectResponse.contours:type_name -> detector.Contour
	0, // 2: detector.ObjectDetector.Detect:input_type -> detector.DetectRequest
	3, // 3: detector.ObjectDetector.Detect:output_type -> detector.DetectResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_detector_proto_detector_proto_init() }
func file_internal_transport_grpc_detector_proto_detector_proto_init() {
	if File_internal_transport_grpc_detector_proto_detector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_detector_proto_detector_proto_rawDesc), len(file_internal_transport_grpc_detector_proto_detector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_detector_proto_detector_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_detector_proto_detector_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_detector_proto_detector_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_detector_proto_detector_proto = out.File
	file_internal_transport_grpc_detector_proto_detector_proto_goTypes = nil
	file_internal_transport_grpc_detector_proto_detector_proto_depIdxs = nil
}
