// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/transport/grpc/detector/proto/detector.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObjectDetector_Detect_FullMethodName = "/detector.ObjectDetector/Detect"
)

// ObjectDetectorClient is the client API for ObjectDetector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectDetectorClient interface {
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
}

type objectDetectorClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectDetectorClient(cc grpc.ClientConnInterface) ObjectDetectorClient {
	return &objectDetectorClient{cc}
}

func (c *objectDetectorClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, ObjectDetector_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectDetectorServer is the server API for ObjectDetector service.
// All implementations must embed UnimplementedObjectDetectorServer
// for forward compatibility.
type ObjectDetectorServer interface {
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	mustEmbedUnimplementedObjectDetectorServer()
}

// UnimplementedObjectDetectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObjectDetectorServer struct{}

func (UnimplementedObjectDetectorServer) Detect(context.Context, *DetectRequest) (*DetectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedObjectDetectorServer) mustEmbedUnimplementedObjectDetectorServer() {}
func (UnimplementedObjectDetectorServer) testEmbeddedByValue()                        {}

// UnsafeObjectDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectDetectorServer will
// result in compilation errors.
type UnsafeObjectDetectorServer interface {
	mustEmbedUnimplementedObjectDetectorServer()
}

func RegisterObjectDetectorServer(s grpc.ServiceRegistrar, srv ObjectDetectorServer) {
	// If the following call pancis, it indicates UnimplementedObjectDetectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObjectDetector_ServiceDesc, srv)
}

func _ObjectDetector_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectDetectorServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectDetector_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectDetectorServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectDetector_ServiceDesc is the grpc.ServiceDesc for ObjectDetector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectDetector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "detector.ObjectDetector",
	HandlerType: (*ObjectDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _ObjectDetector_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/transport/grpc/detector/proto/detector.proto",
}
